 
services:
  db:
    image: postgres:16.8
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: jobs_zl
    volumes:
      - ./postgres:/var/lib/postgresql/data
